config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sons
  resources :fathers
  get 'uploads/new'

  get 'image/download' => 'pictures#download'

  resources :orders
  get 'search', to: 'search#search'

  resources :pictures
  resources :articles
  
  resources :posts

  namespace :api do
    namespace :v1 do
      resources :posts
      resources :users
    end
  end

  resources :uploads

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users

  root to: 'pictures#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, :description, presence: true
end

app/models/father.rb
class Father < ActiveRecord::Base
  has_many :sons

  accepts_nested_attributes_for :sons
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :image

  validates_attachment :image, 
                        presence: true,
                        content_type: { content_type: /\Aimage\/.*\Z/ },
                        size: { less_than: 5.megabyte }

  validates :name, :description, presence: true

  def paypal_url(return_path)
    values = {
      business: "satoshy@ya.ru",
      cmd: "_xclick",
      upload: 1,
      return: "#{Rails.application.secrets.app_host}#{return_path}",
      invoice: id,
      amount: course.price,
      item_name: course.name,
      item_number: course.id,
      quantity: '1',
      notify_url: "#{Rails.application.secrets.app_host}/hook"
    }
    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
  validates :name, :description, presence: true
end

app/models/son.rb
class Son < ActiveRecord::Base
  belongs_to :father
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_attached_file :image

  validates_attachment :image, 
                        presence: true,
                        content_type: { content_type: /\Aimage\/.*\Z/ },
                        size: { less_than: 1.megabyte }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :articles, dependent: :destroy

  after_create :send_mail

  def send_mail
    UserMailer.new_user_registration(self).deliver_now
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def show
  end

  def new
    @picture = Picture.new
  end

  def edit
  end

  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    send_file(params[:path])
  end

  private
    def set_picture
      @picture = Picture.find(params[:id])
    end

    def picture_params
      params.require(:picture).permit(:name, :description, {images: []}, :images_cache)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :description)
    end
end

app/controllers/sons_controller.rb
class SonsController < ApplicationController
  before_action :set_son, only: [:show, :edit, :update, :destroy]

  def index
    @sons = Son.all
  end

  def show
  end

  def new
    @son = Son.new
  end

  def edit
  end

  def create
    @son = Son.new(son_params)

    respond_to do |format|
      if @son.save
        format.html { redirect_to @son, notice: 'Son was successfully created.' }
        format.json { render :show, status: :created, location: @son }
      else
        format.html { render :new }
        format.json { render json: @son.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @son.update(son_params)
        format.html { redirect_to @son, notice: 'Son was successfully updated.' }
        format.json { render :show, status: :ok, location: @son }
      else
        format.html { render :edit }
        format.json { render json: @son.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @son.destroy
    respond_to do |format|
      format.html { redirect_to sons_url, notice: 'Son was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_son
      @son = Son.find(params[:id])
    end

    def son_params
      params.require(:son).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show]
  
  def index 
    @users = User.all 
  end

  def show 
    @user = User.find(params[:id])
  end

  private
    def load_user 
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/fathers_helper.rb
module FathersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sons_helper.rb
module SonsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture, html: { multipart: true, class: "dropzone" }) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="fallback dropzone">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.name %></td>
        <td><%= picture.description %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>

<p>
	<strong>Images</strong>
	<% @picture.images.map do |image| %>
	  <table>
	    <tr>
	      <td><%= image_tag(image) %></td>
	      <td><%= link_to "#{image.file.basename}", image_download_path(path: image.current_path.to_s) %></td>
	    </tr>
	   </table>
	<% end %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>